version: "3"
services:
    backend:
        build:
            context: ./backend
            args:
                ENV: development
        ports:
            - '3000:3000'
        volumes:
            - ./backend:/backend
        restart: unless-stopped
        networks:
            - app-network
        environment:
            PORT: "3000"

networks:
    app-network:
        driver: bridge